default: &default
  database: kabel-sm_production
  username: postgres
  password: 860827
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kabel-sm_development
test:
  <<: *default
  database: kabel-sm_test

production:
  <<: *default
  database: kabel-sm_production
  username: kabel-sm
  password: <%= ENV['KABEL-SM_DATABASE_PASSWORD'] %>
